name: Daily SharePoint Upload

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8:00 UTC (9am UK time during BST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
      SP_SITE_URL: ${{ secrets.SP_SITE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r monitoring_data_collection_tool_github_actions/requirements.txt

      - name: Run workflow script
        run: python monitoring_data_collection_tool_github_actions/run.py
